export class IconsNames {
  static ShoppingCart = 'shopping_cart';
  static Search = 'search';
  static KeyboardArrowDown = 'keyboard_arrow_down';
  static Home = 'home';
  static ArrowBack = 'arrow_back';
  static ArrowForward = 'arrow_forward';
  static ChevronLeft = 'chevron_left';
  static ChevronRight = 'chevron_right';
  static LibraryAdd = 'library_add'
  static Identity = 'perm_identity';
  static AccountCircle = 'account_circle';
  static Face = 'face';
  static Person = 'person';
  static Cancel = 'cancel';
  static ExitToApp = 'exit_to_app';
  static LocalDining = 'local_dining';
  static Settings = 'settings';
  static AddBox = 'add_box';
  static Done = 'done';
  static MoreHorizontal = 'more_horiz';
  static MoreVertical = 'more_vert';
}
