export class FrontendSelectorsIds {
  static CreateCollectionItemSelector = 'fw-create-collection-item';
  static BaseCollectionSelector = 'fw-base-collection';
  static BaseCollectionItemSelector = 'fw-base-collection-item';
  static BaseUpdateSelector = 'fw-base-update';
  static HomeSelector = 'fw-home';
  static DashboardSelector = 'fw-dashboard';
  static DashboardWindowSelector = 'fw-dashboard-window';
  static DashboardHeaderSelector = 'fw-dashboard-header';
  static SidebarPrimarySelector = 'fw-sidebar-primary';
  static SidebarSecondarySelector = 'fw-sidebar-secondary';
  static SidebarPrimaryItemSelector = 'fw-sidebar-primary-item';
  static SidebarSecondaryItemSelector = 'fw-sidebar-secondary-item';
  static HeaderSelector = 'fw-header';
  static PageNotFoundSelector = 'fw-404';
  static DashboardTileSelector = 'fw-tile';
  static CollectionTileSelector = 'fw-collection-tile';
  static DashboardPanelSelector = 'fw-dashboard-panel';
  static ActionsPanelSelector = 'fw-actions-panel';
  static ActionButtonSelector = 'fw-action-button';
  static HeaderNavigationButtonSelector = 'fw-header-nav-button';
  static AlertSelector = 'fw-alert';
  static AlertModalSelector = 'fw-alert-modal';
  static LoginSelector = 'fw-login';
  static HeaderAuthenticationSelector = 'fw-header-auth';
  static FileImageSelector = 'fw-file-image';
  static BaseAction = 'fw-base-action';
  static HeaderActionItemSelector = 'fw-header-action-item';
  static HeaderActionsPanelSelector = 'fw-header-actions-panel';
  static CollectionItemActionItemSelector = 'fw-collection-item-action-item';
}

